var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/news/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__fed0bd85._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_ff9dfe7e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b6e402dc._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_3fe18255._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_news_page_actions_884ddb1a.js")
R.m(93595)
module.exports=R.m(93595).exports
