var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/footer/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__c5b61c7d._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_6dbccd64._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b6e402dc._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_3fe18255._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_admin_01b1e832._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_footer_page_actions_b1b89a2f.js")
R.m(26470)
module.exports=R.m(26470).exports
