var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/news/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__be952a22._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_2bb25fa5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b6e402dc._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_3fe18255._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_admin_01b1e832._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_news_page_actions_d0da2703.js")
R.m(2791)
module.exports=R.m(2791).exports
