var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/personnel/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__de6add15._.js")
R.c("server/chunks/ssr/_6139f1ce._.js")
R.c("server/chunks/ssr/_babb6ed8._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b6e402dc._.js")
R.c("server/chunks/ssr/node_modules_722875e3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/app_3fe18255._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/app_admin_01b1e832._.js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_personnel_page_actions_15b740fd.js")
R.m(73208)
module.exports=R.m(73208).exports
